# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: André's Academic Profile
subtitle: Education, research interests, and more
email: andre-costa@ufmg.br
description: Personal page for academic information. Member of Operations Research and Complex Systems Laboratory (ORCS Lab/UFMG). >- # this means to ignore newlines until "baseurl:"
twitter_username: andrecbatista
github_username: andre-batista
minimal_mistakes_skin: 'mint'
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "André Batista"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Ph.D. canditate at Graduate Program in Electrical Engineering, Universidade Federal de Minas Gerais (Brazil)."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:adnre-costa@ufmg.br"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andre-batista"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=a00NW34AAAAJ&hl=pt-BR"
    - label: "CV Lattes [PT]"
      icon: "fas fa-fw fa-link"
      url: "http://lattes.cnpq.br/2956055711847042"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/andrecbatista"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:adnre-costa@ufmg.br"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andre-batista"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=a00NW34AAAAJ&hl=pt-BR"
    - label: "CV Lattes [PT]"
      icon: "fas fa-fw fa-link"
      url: "http://lattes.cnpq.br/2956055711847042"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/andrecbatista"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/